//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ddd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime registerDate { get; set; }
        public bool isActive { get; set; }
        public string password { get; set; }
        public Nullable<bool> gender { get; set; }
        public string nationalCode { get; set; }
        public string imageName { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<bool> marital { get; set; }
    }
}
